### PR TITLE
Rerendered Using Grayskull - v0.42b0

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@mariusvniekerk - Ready for Review !
Thank you and Regards.

**Comment by rxm7706** [comment]
Hi @mariusvniekerk @conda-forge-admin 
Could you please review and merge! Happy to help as a maintainer for Open-telemetry packages - it appears we have almost 40+ packages and dependencies that need updates. 
I have some Open PRs and Analysis ready at 
https://github.com/conda-forge/opentelemetry-sdk-feedstock/pull/31
https://github.com/conda-forge/opentelemetry-exporter-otlp-proto-common-feedstock/pull/8

**Comment by timostrunk** [comment]
@mariusvniekerk We need to get these through the stack, because for many people this forces opentelemetry-semantic-conventions to 0.37b, which is vulnerable, as some dependencies were not built intermittently.

**Comment by rxm7706** [comment]
Superseded by https://github.com/conda-forge/opentelemetry-semantic-conventions-feedstock/pull/28

**Pull request closed without merging**
